version: '3'

services:

  server:
    image: nginx:alpine
    restart: always
    depends_on:
      - web
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./public:/code/public
  
  web:
    image: xwisert/jenkins-example:latest
    command: sh -c "/code/run.sh"
    restart: always
    env_file:
      - .env
    depends_on:
      - app_database
    volumes:
      - ./public:/code/public

  app_database:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - ./postgresql/dumps:/code/dumps
      - ./postgresql/data:/var/lib/pgsql/data
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
